# Configuration adapted from https://github.com/dkhamsing/awesome_bot

## This is a CI-assisted way for validating the links

language: ruby
rvm: 2.4.1
before_script: gem install awesome_bot
script: awesome_bot *.md --allow-redirect --allow-ssl --allow-dupe
notifications:
  email: false
  